# Generated by Django 5.1.1 on 2024-11-03 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmessage',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='subject',
        ),
    ]
